EveryFit/src/main/java/com/kh/EveryFit/dto/JungmoDto.java, EveryFit/src/main/java/com/kh/EveryFit/dto/JungmoMember.java, EveryFit/src/main/java/com/kh/EveryFit/dto/MoimDto.java, EveryFit/src/main/java/com/kh/EveryFit/dto/MoimMemberDto.java, EveryFit/src/main/resources/application.properties
properties 수정
moim, jungmo Dto 생성
=> properties 수정 및 Dto 생성

EveryFit/src/main/resources/application.properties
application.properties 수정했습니다.
=> application.properties 수정

EveryFit/src/main/java/com/kh/EveryFit/controller/MoimController.java, EveryFit/src/main/resources/application.properties, EveryFit/src/main/resources/mybatis/moim-mapper.xml
MoimController 생성
view resolver 추가
=> moim-mapper 생성 등

EveryFit/src/main/webapp/WEB-INF/views/template/Footer.jsp, EveryFit/src/main/webapp/WEB-INF/views/template/Header.jsp
=> 헤더링크 수정, 풋터 폰트 수정

EveryFit/src/main/java/com/kh/EveryFit/dao/FaqDao.java, EveryFit/src/main/java/com/kh/EveryFit/dao/FaqDaoImpl.java, EveryFit/src/main/java/com/kh/EveryFit/dao/FreeBoardDao.java, EveryFit/src/main/java/com/kh/EveryFit/dao/FreeBoardImpl.java, EveryFit/src/main/java/com/kh/EveryFit/dao/MoimBoardDao.java, EveryFit/src/main/java/com/kh/EveryFit/dao/MoimBoardDaoImpl.java, EveryFit/src/main/java/com/kh/EveryFit/dto/FaqDto.java, EveryFit/src/main/java/com/kh/EveryFit/dto/FreeBoardDto.java, EveryFit/src/main/java/com/kh/EveryFit/restcontroller/FaqRestController.java, EveryFit/src/main/java/com/kh/EveryFit/restcontroller/FreeBoardRestController.java, EveryFit/src/main/java/com/kh/EveryFit/restcontroller/moimBoardRestController.java, EveryFit/src/main/resources/mybatis/faq-mapper.xml, EveryFit/src/main/resources/mybatis/freeBoard-mapper.xml, EveryFit/src/main/resources/mybatis/moimBoard-mapper.xml
=> 자유게시판,FAQ,모임게시판 CRUD 구현

EveryFit/src/main/java/com/kh/EveryFit/dao/FreeBoardImpl.java, EveryFit/src/main/java/com/kh/EveryFit/restcontroller/FreeBoardRestController.java, EveryFit/src/main/resources/application.properties, EveryFit/src/main/resources/mybatis/faq-mapper.xml, EveryFit/src/main/resources/mybatis/freeBoard-mapper.xml, EveryFit/src/main/resources/mybatis/moimBoard-mapper.xml
=> 게시판 CRUD 오류 수정

EveryFit/src/main/java/com/kh/EveryFit/controller/MoimController.java, EveryFit/src/main/java/com/kh/EveryFit/dao/JungmoDao.java, EveryFit/src/main/java/com/kh/EveryFit/dao/JungmoDaoImpl.java, EveryFit/src/main/java/com/kh/EveryFit/dao/MemberDao.java, EveryFit/src/main/java/com/kh/EveryFit/dao/MemberDaoImpl.java, EveryFit/src/main/java/com/kh/EveryFit/rest/MoimRestController.java, EveryFit/src/main/java/com/kh/EveryFit/vo/JungmoListByMoimNoVO.java, EveryFit/src/main/resources/mybatis/member-mapper.xml, EveryFit/src/main/resources/mybatis/moim-mapper.xml, EveryFit/src/main/webapp/WEB-INF/views/moim/create.jsp, EveryFit/src/main/webapp/WEB-INF/views/moim/detail.jsp, EveryFit/src/main/webapp/WEB-INF/views/template/Footer.jsp, EveryFit/src/main/webapp/WEB-INF/views/template/Header.jsp
=> 정모 CRUD 구현 중

EveryFit/src/main/java/com/kh/EveryFit/controller/MoimController.java, EveryFit/src/main/java/com/kh/EveryFit/dao/MoimDao.java, EveryFit/src/main/java/com/kh/EveryFit/dao/MoimDaoImpl.java, EveryFit/src/main/java/com/kh/EveryFit/dto/JungmoDto.java, EveryFit/src/main/java/com/kh/EveryFit/rest/AttachRestController.java, EveryFit/src/main/java/com/kh/EveryFit/rest/MoimRestController.java, EveryFit/src/main/resources/mybatis/attach-mapper.xml, EveryFit/src/main/resources/mybatis/moim-mapper.xml, EveryFit/src/main/webapp/WEB-INF/views/moim/create.jsp, EveryFit/src/main/webapp/WEB-INF/views/moim/detail.jsp, EveryFit/src/main/webapp/WEB-INF/views/moim/jungmoCreate.jsp
=> 정모 등록 및 목록조회 구현 중

EveryFit/src/main/java/com/kh/EveryFit/controller/MoimController.java, EveryFit/src/main/java/com/kh/EveryFit/dao/JungmoDao.java, EveryFit/src/main/java/com/kh/EveryFit/dao/JungmoDaoImpl.java, EveryFit/src/main/java/com/kh/EveryFit/dao/MoimDao.java, EveryFit/src/main/java/com/kh/EveryFit/dao/MoimDaoImpl.java, EveryFit/src/main/java/com/kh/EveryFit/dto/JungmoMemberDto.java, EveryFit/src/main/java/com/kh/EveryFit/rest/AttachRestController.java, EveryFit/src/main/java/com/kh/EveryFit/rest/MoimRestController.java, EveryFit/src/main/java/com/kh/EveryFit/vo/JungmoListByMoimNoVO.java, EveryFit/src/main/java/com/kh/EveryFit/vo/JungmoListVO.java, EveryFit/src/main/java/com/kh/EveryFit/vo/JungmoMemberListVO.java, EveryFit/src/main/java/com/kh/EveryFit/vo/JungmoWithMembersVO.java, EveryFit/src/main/resources/mybatis/moim-mapper.xml, EveryFit/src/main/webapp/WEB-INF/views/moim/create.jsp, EveryFit/src/main/webapp/WEB-INF/views/moim/detail.jsp, EveryFit/src/main/webapp/WEB-INF/views/moim/jungmoCreate.jsp
정모 프로필사진, 회원 참가/취소, 정모 list, 정모멤버list 구현 중
모임/정모 파일첨부 및 등록 구현
=> Soeun정모 정보 수정 / 모임 정보 수정 구현 중

EveryFit/src/main/java/com/kh/EveryFit/controller/FreeBoardController.java, EveryFit/src/main/java/com/kh/EveryFit/controller/MemberController.java, EveryFit/src/main/java/com/kh/EveryFit/dao/FreeBoardDao.java, EveryFit/src/main/java/com/kh/EveryFit/dao/FreeBoardImpl.java, EveryFit/src/main/webapp/WEB-INF/views/freeBoard/list.jsp, EveryFit/src/main/webapp/WEB-INF/views/member/join.jsp, EveryFit/src/main/webapp/WEB-INF/views/template/Header.jsp
=> 헤더 로그인 로그아웃 표시

EveryFit/src/main/java/com/kh/EveryFit/controller/FreeBoardController.java, EveryFit/src/main/java/com/kh/EveryFit/controller/MemberController.java, EveryFit/src/main/java/com/kh/EveryFit/dao/FreeBoardDao.java, EveryFit/src/main/java/com/kh/EveryFit/dao/FreeBoardImpl.java, EveryFit/src/main/webapp/WEB-INF/views/freeBoard/add.jsp, EveryFit/src/main/webapp/WEB-INF/views/freeBoard/detail.jsp, EveryFit/src/main/webapp/WEB-INF/views/freeBoard/edit.jsp, EveryFit/src/main/webapp/WEB-INF/views/freeBoard/list.jsp, EveryFit/src/main/webapp/WEB-INF/views/template/Header.jsp
=> 디자인을 제외한 자유게시판

EveryFit/src/main/webapp/WEB-INF/views/freeBoard/detail.jsp, EveryFit/src/main/webapp/WEB-INF/views/freeBoard/edit.jsp, EveryFit/src/main/webapp/WEB-INF/views/freeBoard/list.jsp, EveryFit/src/main/webapp/WEB-INF/views/template/Footer.jsp, EveryFit/src/main/webapp/WEB-INF/views/template/Header.jsp
=> 게시판 디자인 일부 수정(풋터 변경 예정)

EveryFit/src/main/java/com/kh/EveryFit/controller/FaqController.java, EveryFit/src/main/java/com/kh/EveryFit/dao/FaqDao.java, EveryFit/src/main/java/com/kh/EveryFit/dao/FaqDaoImpl.java, EveryFit/src/main/webapp/WEB-INF/views/faq/add.jsp, EveryFit/src/main/webapp/WEB-INF/views/faq/detail.jsp, EveryFit/src/main/webapp/WEB-INF/views/faq/edit.jsp, EveryFit/src/main/webapp/WEB-INF/views/faq/list.jsp, EveryFit/src/main/webapp/WEB-INF/views/template/Header.jsp
=> faq게시판 기능 구현, 헤더 검색 버튼 색상 변경

EveryFit/src/main/java/com/kh/EveryFit/controller/FaqController.java, EveryFit/src/main/resources/mybatis/faq-mapper.xml, EveryFit/src/main/webapp/WEB-INF/views/faq/add.jsp, EveryFit/src/main/webapp/WEB-INF/views/freeBoard/list.jsp
=> faq 게시판 CRUD 오류 수정

EveryFit/src/main/java/com/kh/EveryFit/controller/FaqController.java, EveryFit/src/main/java/com/kh/EveryFit/controller/FreeBoardController.java, EveryFit/src/main/resources/mybatis/faq-mapper.xml, EveryFit/src/main/resources/mybatis/freeBoard-mapper.xml, EveryFit/src/main/webapp/WEB-INF/views/faq/add.jsp, EveryFit/src/main/webapp/WEB-INF/views/faq/detail.jsp, EveryFit/src/main/webapp/WEB-INF/views/faq/edit.jsp, EveryFit/src/main/webapp/WEB-INF/views/faq/list.jsp, EveryFit/src/main/webapp/WEB-INF/views/freeBoard/add.jsp, EveryFit/src/main/webapp/WEB-INF/views/freeBoard/detail.jsp, EveryFit/src/main/webapp/WEB-INF/views/freeBoard/edit.jsp, EveryFit/src/main/webapp/WEB-INF/views/freeBoard/list.jsp, EveryFit/src/main/webapp/WEB-INF/views/template/Header.jsp
=> 자유게시판,FAQ 게시판 수정, 등록  디자인 추가

EveryFit/src/main/webapp/WEB-INF/views/home.jsp, EveryFit/src/main/webapp/WEB-INF/views/template/Footer.jsp, EveryFit/src/main/webapp/WEB-INF/views/template/adminHeader.jsp
=> 관리자 헤더 추가(임시) 표시

EveryFit/src/main/webapp/WEB-INF/views/freeBoard/list.jsp, EveryFit/src/main/webapp/WEB-INF/views/template/Footer.jsp, EveryFit/src/main/webapp/WEB-INF/views/template/Header.jsp, EveryFit/src/main/webapp/WEB-INF/views/template/adminHeader.jsp
=> 풋터 위치 하단 포지션 수정

EveryFit/src/main/java/com/kh/EveryFit/dao/FreeBoardDao.java, EveryFit/src/main/java/com/kh/EveryFit/dao/FreeBoardImpl.java, EveryFit/src/main/java/com/kh/EveryFit/vo/BoardVO.java, EveryFit/src/main/resources/mybatis/freeBoard-mapper.xml, EveryFit/src/main/webapp/WEB-INF/views/freeBoard/list.jsp, EveryFit/src/main/webapp/WEB-INF/views/member/join.jsp, EveryFit/src/main/webapp/WEB-INF/views/template/adminHeader.jsp
=> 자유게시판 검색기능 구현중

EveryFit/src/main/java/com/kh/EveryFit/dto/FreeBoardReplyDto.java, EveryFit/src/main/resources/mybatis/freeBoardReply-mapper.xml, EveryFit/src/main/webapp/WEB-INF/views/freeBoard/detail.jsp
=> 자유 게시판 댓글 구현중

EveryFit/src/main/webapp/WEB-INF/views/member/join.jsp
=> 이메일 인증번호 받기 재수정

EveryFit/src/main/java/com/kh/EveryFit/dao/CertDaoImpl.java, EveryFit/src/main/java/com/kh/EveryFit/restcontroller/CertRestController.java, EveryFit/src/main/resources/mybatis/freeBoardReply-mapper.xml, EveryFit/src/main/webapp/WEB-INF/views/member/join.jsp, EveryFit/src/main/webapp/WEB-INF/views/template/Footer.jsp, EveryFit/src/main/webapp/WEB-INF/views/template/Header.jsp, EveryFit/src/main/webapp/WEB-INF/views/template/adminHeader.jsp
회원 가입시  이메일 인증 연동 기능 구현  오류 해결
=> 회원 가입시  이메일 인증 연동 기능 구현  오류 해결

EveryFit/src/main/java/com/kh/EveryFit/dao/FreeBoardReplyDao.java, EveryFit/src/main/java/com/kh/EveryFit/dao/FreeBoardReplyDaoImpl.java, EveryFit/src/main/java/com/kh/EveryFit/rest/FreeBoardReplyRestController.java, EveryFit/src/main/resources/mybatis/freeBoardReply-mapper.xml, EveryFit/src/main/webapp/WEB-INF/views/faq/add.jsp, EveryFit/src/main/webapp/WEB-INF/views/faq/detail.jsp, EveryFit/src/main/webapp/WEB-INF/views/faq/edit.jsp, EveryFit/src/main/webapp/WEB-INF/views/faq/list.jsp, EveryFit/src/main/webapp/WEB-INF/views/freeBoard/add.jsp, EveryFit/src/main/webapp/WEB-INF/views/freeBoard/detail.jsp, EveryFit/src/main/webapp/WEB-INF/views/freeBoard/edit.jsp, EveryFit/src/main/webapp/WEB-INF/views/freeBoard/list.jsp, EveryFit/src/main/webapp/WEB-INF/views/moim/detail.jsp, EveryFit/src/main/webapp/WEB-INF/views/template/Footer.jsp, EveryFit/src/main/webapp/WEB-INF/views/template/Header.jsp
헤더 풋터 위치 오류 수정 및 자유게시판 댓글 컨트롤러 작업중
=> 헤더 풋터 위치 오류 수정 및 자유게시판 댓글 컨트롤러 작업중

EveryFit/src/main/java/com/kh/EveryFit/dao/FreeBoardReplyDao.java, EveryFit/src/main/java/com/kh/EveryFit/dao/FreeBoardReplyDaoImpl.java, EveryFit/src/main/java/com/kh/EveryFit/rest/FreeBoardReplyRestController.java, EveryFit/src/main/java/com/kh/EveryFit/restcontroller/CertRestController.java, EveryFit/src/main/resources/mybatis/freeBoardReply-mapper.xml, EveryFit/src/main/webapp/WEB-INF/views/freeBoard/detail.jsp, EveryFit/src/main/webapp/WEB-INF/views/member/join.jsp, EveryFit/src/main/webapp/WEB-INF/views/template/Header.jsp, EveryFit/src/main/webapp/WEB-INF/views/template/adminHeader.jsp
댓글 페이지 구현중, 회원 이메일 확인 오류 해결, 헤더 회원 마이페이지 추가
=> 댓글 페이지 구현중, 회원 이메일 확인 오류 해결, 헤더 회원 마이페이지 추가

EveryFit/src/main/webapp/WEB-INF/views/faq/list.jsp, EveryFit/src/main/webapp/WEB-INF/views/freeBoard/list.jsp, EveryFit/src/main/webapp/WEB-INF/views/template/Header.jsp, EveryFit/src/main/webapp/WEB-INF/views/template/adminHeader.jsp
헤더 현재시각 표시 기능 구현,  게시판 버튼 스크롤시 회전기능 추가
=> 헤더 현재시각 표시 기능 구현,  게시판 버튼 스크롤시 회전기능 추가

EveryFit/src/main/java/com/kh/EveryFit/dao/FreeBoardDao.java, EveryFit/src/main/java/com/kh/EveryFit/dao/FreeBoardImpl.java, EveryFit/src/main/java/com/kh/EveryFit/dao/FreeBoardReplyDao.java, EveryFit/src/main/java/com/kh/EveryFit/dao/FreeBoardReplyDaoImpl.java, EveryFit/src/main/java/com/kh/EveryFit/dto/FreeBoardDto.java, EveryFit/src/main/java/com/kh/EveryFit/dto/FreeBoardReplyDto.java, EveryFit/src/main/java/com/kh/EveryFit/rest/FreeBoardReplyRestController.java, EveryFit/src/main/resources/mybatis/freeBoard-mapper.xml, EveryFit/src/main/resources/mybatis/freeBoardReply-mapper.xml, EveryFit/src/main/webapp/WEB-INF/views/faq/add.jsp, EveryFit/src/main/webapp/WEB-INF/views/faq/edit.jsp, EveryFit/src/main/webapp/WEB-INF/views/faq/list.jsp, EveryFit/src/main/webapp/WEB-INF/views/freeBoard/add.jsp, EveryFit/src/main/webapp/WEB-INF/views/freeBoard/detail.jsp, EveryFit/src/main/webapp/WEB-INF/views/freeBoard/edit.jsp, EveryFit/src/main/webapp/WEB-INF/views/freeBoard/list.jsp
=> 자유게시판 댓글 기능 구현 완료 (디자인X)

EveryFit/src/main/java/com/kh/EveryFit/controller/MemberController.java, EveryFit/src/main/java/com/kh/EveryFit/dao/FreeBoardDao.java, EveryFit/src/main/java/com/kh/EveryFit/dao/FreeBoardImpl.java, EveryFit/src/main/java/com/kh/EveryFit/rest/FreeBoardAttachRestController.java, EveryFit/src/main/resources/mybatis/freeBoard-mapper.xml, EveryFit/src/main/webapp/WEB-INF/views/freeBoard/add.jsp
=> 자유게시판 파일 업로드 준비

EveryFit/src/main/java/com/kh/EveryFit/controller/FreeBoardController.java, EveryFit/src/main/java/com/kh/EveryFit/dao/FreeBoardDao.java, EveryFit/src/main/java/com/kh/EveryFit/dao/FreeBoardImpl.java, EveryFit/src/main/java/com/kh/EveryFit/dto/FreeBoardDto.java, EveryFit/src/main/java/com/kh/EveryFit/rest/FreeBoardAttachRestController.java, EveryFit/src/main/resources/mybatis/freeBoard-mapper.xml, EveryFit/src/main/webapp/WEB-INF/views/freeBoard/add.jsp, EveryFit/src/main/webapp/WEB-INF/views/freeBoard/detail.jsp
=> 자유 게시판 사진 등록 기능 구현

EveryFit/src/main/java/com/kh/EveryFit/controller/FaqController.java, EveryFit/src/main/java/com/kh/EveryFit/dao/FaqDao.java, EveryFit/src/main/java/com/kh/EveryFit/dao/FaqDaoImpl.java, EveryFit/src/main/java/com/kh/EveryFit/dao/FreeBoardImpl.java, EveryFit/src/main/java/com/kh/EveryFit/rest/FAQAttachRestController.java, EveryFit/src/main/resources/mybatis/faq-mapper.xml, EveryFit/src/main/webapp/WEB-INF/views/faq/add.jsp, EveryFit/src/main/webapp/WEB-INF/views/faq/detail.jsp, EveryFit/src/main/webapp/WEB-INF/views/faq/edit.jsp, EveryFit/src/main/webapp/WEB-INF/views/freeBoard/edit.jsp
=> FAQ 게시판 사진 파일 전송 기능 구현

EveryFit/src/main/java/com/kh/EveryFit/controller/MoimController.java, EveryFit/src/main/java/com/kh/EveryFit/dao/MoimDao.java, EveryFit/src/main/java/com/kh/EveryFit/dao/MoimDaoImpl.java, EveryFit/src/main/java/com/kh/EveryFit/rest/MoimRestController.java, EveryFit/src/main/java/com/kh/EveryFit/service/ChannelServiceImpl.java, EveryFit/src/main/java/com/kh/EveryFit/vo/MoimMemberStatusVO.java, EveryFit/src/main/java/com/kh/EveryFit/websocket/ChatWebsocketServer.java, EveryFit/src/main/resources/mybatis/chat-mapper.xml, EveryFit/src/main/resources/mybatis/moim-mapper.xml, EveryFit/src/main/webapp/WEB-INF/views/moim/create.jsp, EveryFit/src/main/webapp/WEB-INF/views/moim/detail.jsp, EveryFit/src/main/webapp/WEB-INF/views/moim/jungmoCreate.jsp, EveryFit/src/main/webapp/WEB-INF/views/ws/chatList.jsp, EveryFit/src/main/webapp/WEB-INF/views/ws/default.jsp
=> 모임 멤버 상태 차단/승인 변경 구현, 모임/정모 정보 수정 구현 중

EveryFit/src/main/webapp/WEB-INF/views/faq/add.jsp, EveryFit/src/main/webapp/WEB-INF/views/faq/edit.jsp, EveryFit/src/main/webapp/WEB-INF/views/freeBoard/add.jsp, EveryFit/src/main/webapp/WEB-INF/views/freeBoard/edit.jsp
=> 자유게시판, FAQ 글 작성,수정 디자인 변경

EveryFit/src/main/java/com/kh/EveryFit/dao/MoimDao.java, EveryFit/src/main/java/com/kh/EveryFit/dao/MoimDaoImpl.java, EveryFit/src/main/java/com/kh/EveryFit/rest/MoimRestController.java, EveryFit/src/main/java/com/kh/EveryFit/restcontroller/moimBoardRestController.java, EveryFit/src/main/resources/mybatis/moim-mapper.xml, EveryFit/src/main/webapp/WEB-INF/views/moim/detail.jsp
=> 모임 정보 변경 구현

EveryFit/src/main/webapp/WEB-INF/views/admin/memberList.jsp, EveryFit/src/main/webapp/WEB-INF/views/admin/mypage.jsp, EveryFit/src/main/webapp/WEB-INF/views/freeBoard/list.jsp
=> 관리자 회원 검색기능 구현중

EveryFit/src/main/java/com/kh/EveryFit/dto/MemberDto.java, EveryFit/src/main/java/com/kh/EveryFit/service/MemberService.java, EveryFit/src/main/java/com/kh/EveryFit/service/MemberServiceImpl.java, EveryFit/src/main/webapp/WEB-INF/views/member/change.jsp, EveryFit/src/main/webapp/WEB-INF/views/member/findPw.jsp, EveryFit/src/main/webapp/WEB-INF/views/member/findPwFinish.jsp, EveryFit/src/main/webapp/WEB-INF/views/member/login.jsp, EveryFit/src/main/webapp/WEB-INF/views/member/mypage.jsp
=> 로그인,회원가입,이메일인증,회원정보변경,회원탈퇴

EveryFit/src/main/java/com/kh/EveryFit/configuration/EmptyStringControllerAdvice.java, EveryFit/src/main/java/com/kh/EveryFit/controller/AdminController.java, EveryFit/src/main/java/com/kh/EveryFit/dao/AdminDao.java, EveryFit/src/main/java/com/kh/EveryFit/dao/AdminDaoImpl.java, EveryFit/src/main/java/com/kh/EveryFit/vo/AdminMemberSearchVO.java, EveryFit/src/main/resources/mybatis/admin-mapper.xml, EveryFit/src/main/webapp/WEB-INF/views/admin/memberList.jsp
=> 관리자의 회원 상세 검색 기능 구현

EveryFit/src/main/java/com/kh/EveryFit/controller/AdminController.java, EveryFit/src/main/java/com/kh/EveryFit/dao/AdminDao.java, EveryFit/src/main/java/com/kh/EveryFit/dao/AdminDaoImpl.java, EveryFit/src/main/java/com/kh/EveryFit/vo/AdminMoimSearchVO.java, EveryFit/src/main/resources/mybatis/admin-mapper.xml, EveryFit/src/main/webapp/WEB-INF/views/admin/moimList.jsp, EveryFit/src/main/webapp/WEB-INF/views/template/adminHeader.jsp
=> 관리자 모임 검색 구현중 임시저장

EveryFit/src/main/java/com/kh/EveryFit/controller/AdminController.java, EveryFit/src/main/java/com/kh/EveryFit/vo/AdminMoimSearchVO.java, EveryFit/src/main/resources/mybatis/admin-mapper.xml, EveryFit/src/main/webapp/WEB-INF/views/admin/moimList.jsp
=> 관리자 모임검색 준비중

EveryFit/src/main/resources/mybatis/moim-mapper.xml, EveryFit/src/main/webapp/WEB-INF/views/moim/detail.jsp
=> 오류 수정 및 정모 입력/수정 모달창으로 구현 중

EveryFit/src/main/java/com/kh/EveryFit/controller/AdminController.java, EveryFit/src/main/java/com/kh/EveryFit/dao/AdminDao.java, EveryFit/src/main/java/com/kh/EveryFit/dao/AdminDaoImpl.java, EveryFit/src/main/java/com/kh/EveryFit/vo/AdminJungmoSearchVO.java, EveryFit/src/main/resources/mybatis/admin-mapper.xml, EveryFit/src/main/webapp/WEB-INF/views/admin/jungmoList.jsp, EveryFit/src/main/webapp/WEB-INF/views/admin/moimList.jsp, EveryFit/src/main/webapp/WEB-INF/views/template/adminHeader.jsp
=> 관리자의 정모 목록 조회 및 상세 검색기능 구현

EveryFit/src/main/java/com/kh/EveryFit/controller/MoimController.java, EveryFit/src/main/java/com/kh/EveryFit/dao/MoimDao.java, EveryFit/src/main/java/com/kh/EveryFit/dao/MoimDaoImpl.java, EveryFit/src/main/java/com/kh/EveryFit/rest/MoimRestController.java, EveryFit/src/main/java/com/kh/EveryFit/vo/JungmoDetailVO.java, EveryFit/src/main/resources/mybatis/moim-mapper.xml, EveryFit/src/main/webapp/WEB-INF/views/moim/create.jsp, EveryFit/src/main/webapp/WEB-INF/views/moim/detail.jsp
모임 등록 시 회원검사 추가
정모수정 모달창 수정(사진이 두번 등록되는 문제)
=> 정모 등록 수정 등 모달로 구현

EveryFit/src/main/java/com/kh/EveryFit/controller/MoimController.java, EveryFit/src/main/java/com/kh/EveryFit/dao/AttachDao.java, EveryFit/src/main/java/com/kh/EveryFit/dao/MoimDao.java, EveryFit/src/main/java/com/kh/EveryFit/dao/MoimDaoImpl.java, EveryFit/src/main/java/com/kh/EveryFit/dto/MoimMemberDto.java, EveryFit/src/main/java/com/kh/EveryFit/vo/ClientVO.java, EveryFit/src/main/java/com/kh/EveryFit/vo/MoimMemberStatusVO.java, EveryFit/src/main/java/com/kh/EveryFit/websocket/ChatWebsocketServer.java, EveryFit/src/main/resources/mybatis/moim-mapper.xml, EveryFit/src/main/webapp/WEB-INF/views/moim/detail.jsp, EveryFit/src/main/webapp/WEB-INF/views/ws/default.jsp
비활성화 상태인 모임상세에 모달창 띄우기 구현
날짜 형식검사 수정
정모 일정 등록/수정 시 형식검사, 모임 탈퇴 구현
=> 웹소켓 회원목록 전송 구현

EveryFit/src/main/webapp/WEB-INF/views/home.jsp, EveryFit/src/main/webapp/WEB-INF/views/member/mypage.jsp
=> 메인페이지 디자인 변경 및 모임 인원 보기 기능 추가

EveryFit/src/main/java/com/kh/EveryFit/controller/HomeController.java, EveryFit/src/main/java/com/kh/EveryFit/dao/AdminDao.java, EveryFit/src/main/java/com/kh/EveryFit/dao/AdminDaoImpl.java, EveryFit/src/main/java/com/kh/EveryFit/rest/HomeRestController.java, EveryFit/src/main/webapp/WEB-INF/views/home.jsp
=> 메인페이지 모임 인원수  손보는중

EveryFit/src/main/java/com/kh/EveryFit/controller/KakaoPayController.java, EveryFit/src/main/java/com/kh/EveryFit/dto/ChatDto.java, EveryFit/src/main/java/com/kh/EveryFit/service/ChannelService.java, EveryFit/src/main/java/com/kh/EveryFit/service/ChannelServiceImpl.java, EveryFit/src/main/java/com/kh/EveryFit/vo/ChatRoomVO.java, EveryFit/src/main/java/com/kh/EveryFit/vo/ClientVO.java, EveryFit/src/main/java/com/kh/EveryFit/websocket/ChatWebsocketServer.java, EveryFit/src/main/resources/mybatis/chat-mapper.xml, EveryFit/src/main/webapp/WEB-INF/views/ws/default.jsp
=> 웹소켓 서버 채팅 구현 중

EveryFit/src/main/java/com/kh/EveryFit/controller/AdminController.java, EveryFit/src/main/java/com/kh/EveryFit/dao/AdminDao.java, EveryFit/src/main/java/com/kh/EveryFit/dao/AdminDaoImpl.java, EveryFit/src/main/java/com/kh/EveryFit/dto/ReportDto.java, EveryFit/src/main/java/com/kh/EveryFit/vo/AdminReportSearchVO.java, EveryFit/src/main/resources/mybatis/admin-mapper.xml, EveryFit/src/main/resources/mybatis/attach-mapper.xml, EveryFit/src/main/webapp/WEB-INF/views/admin/reportList.jsp, EveryFit/src/main/webapp/WEB-INF/views/home.jsp, EveryFit/src/main/webapp/WEB-INF/views/template/adminHeader.jsp
=> 신고 목록 조회 기능 추가

EveryFit/src/main/java/com/kh/EveryFit/controller/HomeController.java, EveryFit/src/main/java/com/kh/EveryFit/dao/AdminDao.java, EveryFit/src/main/java/com/kh/EveryFit/dao/AdminDaoImpl.java, EveryFit/src/main/java/com/kh/EveryFit/vo/AdminMoimMemberCountVO.java, EveryFit/src/main/resources/mybatis/admin-mapper.xml, EveryFit/src/main/webapp/WEB-INF/views/home.jsp
=> 메인페이지 모임 현재인원 출력기능 추가

EveryFit/src/main/java/com/kh/EveryFit/controller/MoimBoradController.java, EveryFit/src/main/java/com/kh/EveryFit/dao/MoimBoardDao.java, EveryFit/src/main/java/com/kh/EveryFit/dao/MoimBoardDaoImpl.java, EveryFit/src/main/java/com/kh/EveryFit/dao/MoimBoardReplyDao.java, EveryFit/src/main/java/com/kh/EveryFit/dao/MoimBoardReplyDaoImpl.java, EveryFit/src/main/java/com/kh/EveryFit/dto/MoimBoardReplyDto.java, EveryFit/src/main/java/com/kh/EveryFit/rest/MoimBoardReplyRestController.java, EveryFit/src/main/resources/mybatis/MoimBoardReply-mapper.xml, EveryFit/src/main/webapp/WEB-INF/views/freeBoard/add.jsp, EveryFit/src/main/webapp/WEB-INF/views/freeBoard/detail.jsp, EveryFit/src/main/webapp/WEB-INF/views/moimBoard/add.jsp, EveryFit/src/main/webapp/WEB-INF/views/moimBoard/detail.jsp, EveryFit/src/main/webapp/WEB-INF/views/moimBoard/list.jsp
=> 모임 게시판 댓글 구현을 위한 준비

EveryFit/src/main/webapp/WEB-INF/views/freeBoard/detail.jsp, EveryFit/src/main/webapp/WEB-INF/views/moimBoard/detail.jsp
=> 모임게시판 댓글 구현

EveryFit/src/main/java/com/kh/EveryFit/controller/FaqController.java, EveryFit/src/main/java/com/kh/EveryFit/controller/FreeBoardController.java, EveryFit/src/main/java/com/kh/EveryFit/controller/MemberController.java, EveryFit/src/main/java/com/kh/EveryFit/controller/MoimBoradController.java, EveryFit/src/main/java/com/kh/EveryFit/dao/FaqDao.java, EveryFit/src/main/java/com/kh/EveryFit/dao/FaqDaoImpl.java, EveryFit/src/main/java/com/kh/EveryFit/dao/FreeBoardDao.java, EveryFit/src/main/java/com/kh/EveryFit/dao/FreeBoardImpl.java, EveryFit/src/main/java/com/kh/EveryFit/dao/MoimBoardDao.java, EveryFit/src/main/java/com/kh/EveryFit/dao/MoimBoardDaoImpl.java, EveryFit/src/main/java/com/kh/EveryFit/dto/FaqDto.java, EveryFit/src/main/java/com/kh/EveryFit/dto/FreeBoardDto.java, EveryFit/src/main/java/com/kh/EveryFit/dto/MoimBoardDto.java, EveryFit/src/main/resources/mybatis/faq-mapper.xml, EveryFit/src/main/resources/mybatis/freeBoard-mapper.xml, EveryFit/src/main/resources/mybatis/moimBoard-mapper.xml, EveryFit/src/main/webapp/WEB-INF/views/faq/list.jsp, EveryFit/src/main/webapp/WEB-INF/views/freeBoard/list.jsp, EveryFit/src/main/webapp/WEB-INF/views/moimBoard/list.jsp
=> 모든 게시판 게시글 레이아웃 수정 및 시간 기능 추가

EveryFit/src/main/java/com/kh/EveryFit/controller/AdminController.java, EveryFit/src/main/java/com/kh/EveryFit/controller/ReportController.java, EveryFit/src/main/java/com/kh/EveryFit/dao/AdminDao.java, EveryFit/src/main/java/com/kh/EveryFit/dao/AdminDaoImpl.java, EveryFit/src/main/java/com/kh/EveryFit/dto/ReportDto.java, EveryFit/src/main/resources/mybatis/admin-mapper.xml, EveryFit/src/main/webapp/WEB-INF/views/admin/mypage.jsp, EveryFit/src/main/webapp/WEB-INF/views/admin/reportList.jsp, EveryFit/src/main/webapp/WEB-INF/views/faq/list.jsp, EveryFit/src/main/webapp/WEB-INF/views/report/apply.jsp, EveryFit/src/main/webapp/WEB-INF/views/report/detail.jsp
=> 신고 작성,상세 기능추가 및 회원 차단 준비중

EveryFit/src/main/java/com/kh/EveryFit/vo/AdminReportSearchVO.java, EveryFit/src/main/resources/mybatis/admin-mapper.xml, EveryFit/src/main/webapp/WEB-INF/views/admin/jungmoList.jsp, EveryFit/src/main/webapp/WEB-INF/views/admin/memberList.jsp, EveryFit/src/main/webapp/WEB-INF/views/admin/moimList.jsp, EveryFit/src/main/webapp/WEB-INF/views/admin/reportList.jsp, EveryFit/src/main/webapp/WEB-INF/views/faq/detail.jsp, EveryFit/src/main/webapp/WEB-INF/views/faq/list.jsp, EveryFit/src/main/webapp/WEB-INF/views/freeBoard/detail.jsp, EveryFit/src/main/webapp/WEB-INF/views/freeBoard/list.jsp, EveryFit/src/main/webapp/WEB-INF/views/moimBoard/detail.jsp, EveryFit/src/main/webapp/WEB-INF/views/moimBoard/list.jsp, EveryFit/src/main/webapp/WEB-INF/views/report/apply.jsp, EveryFit/src/main/webapp/WEB-INF/views/template/Header.jsp, EveryFit/src/main/webapp/WEB-INF/views/template/adminHeader.jsp
관리자 날짜 검색기능 오류 수정 및 신고목록 검색 수정
=> 관리자 날짜 검색기능 오류 수정 및 신고목록 검색 수정

EveryFit/src/main/java/com/kh/EveryFit/dao/MoimDao.java, EveryFit/src/main/java/com/kh/EveryFit/dao/MoimDaoImpl.java, EveryFit/src/main/java/com/kh/EveryFit/rest/MoimRestController.java, EveryFit/src/main/java/com/kh/EveryFit/vo/moimListForMyPageVO.java, EveryFit/src/main/resources/mybatis/moim-mapper.xml, EveryFit/src/main/webapp/WEB-INF/views/member/mypage.jsp, EveryFit/src/main/webapp/WEB-INF/views/pay/premium.jsp
=> 마이페이지에서 비동기로 나의 모임 내역 가져오기

EveryFit/src/main/java/com/kh/EveryFit/controller/AdminController.java, EveryFit/src/main/java/com/kh/EveryFit/controller/ReportController.java, EveryFit/src/main/java/com/kh/EveryFit/dao/AdminDao.java, EveryFit/src/main/java/com/kh/EveryFit/dao/AdminDaoImpl.java, EveryFit/src/main/java/com/kh/EveryFit/rest/ReportAttachRestController.java, EveryFit/src/main/resources/mybatis/admin-mapper.xml, EveryFit/src/main/webapp/WEB-INF/views/report/apply.jsp, EveryFit/src/main/webapp/WEB-INF/views/report/detail.jsp, EveryFit/src/main/webapp/WEB-INF/views/template/adminHeader.jsp
=> 신고기능 사진 전송기능 구현

EveryFit/src/main/java/com/kh/EveryFit/configuration/InterceptorConfiguration.java, EveryFit/src/main/java/com/kh/EveryFit/controller/AdminController.java, EveryFit/src/main/java/com/kh/EveryFit/dao/AdminDao.java, EveryFit/src/main/java/com/kh/EveryFit/dao/AdminDaoImpl.java, EveryFit/src/main/java/com/kh/EveryFit/dto/MemberDto.java, EveryFit/src/main/java/com/kh/EveryFit/interceptor/AdminOwnerInterceptor.java, EveryFit/src/main/resources/mybatis/admin-mapper.xml, EveryFit/src/main/webapp/WEB-INF/views/admin/mypage.jsp
=> 관리자 버튼으로 회원 차단 기능 구현

EveryFit/src/main/java/com/kh/EveryFit/dao/MoimDao.java, EveryFit/src/main/java/com/kh/EveryFit/dao/MoimDaoImpl.java, EveryFit/src/main/java/com/kh/EveryFit/dto/MoimDto.java, EveryFit/src/main/java/com/kh/EveryFit/service/PaymentScheduler.java, EveryFit/src/main/resources/mybatis/moim-mapper.xml
스케줄러로 정기결제시 moim 테이블의 endtime도 정기결제된날짜+1달로 업데이트되도록 구현
=> 스케줄러로 정기결제시 moim 테이블의 endtime도 정기결제된날짜+1달로 업데이트되도록 구현

EveryFit/src/main/java/com/kh/EveryFit/configuration/InterceptorConfiguration.java, EveryFit/src/main/java/com/kh/EveryFit/interceptor/MemberBlockInterceptor.java
=> 인터셉터 오류 수정

EveryFit/src/main/java/com/kh/EveryFit/controller/HomeController.java, EveryFit/src/main/java/com/kh/EveryFit/dao/AdminDao.java, EveryFit/src/main/java/com/kh/EveryFit/dao/AdminDaoImpl.java, EveryFit/src/main/resources/mybatis/admin-mapper.xml, EveryFit/src/main/webapp/WEB-INF/views/home.jsp, EveryFit/src/main/webapp/WEB-INF/views/homeMoimSerach.jsp, EveryFit/src/main/webapp/WEB-INF/views/template/Header.jsp, EveryFit/src/main/webapp/WEB-INF/views/template/adminHeader.jsp
=> 홈페이지에서 검색기능 구현 (디자인X)

EveryFit/src/main/java/com/kh/EveryFit/controller/HomeController.java, EveryFit/src/main/java/com/kh/EveryFit/controller/ReportController.java, EveryFit/src/main/java/com/kh/EveryFit/dto/ReportDto.java, EveryFit/src/main/java/com/kh/EveryFit/vo/AdminReportSearchVO.java, EveryFit/src/main/resources/mybatis/admin-mapper.xml, EveryFit/src/main/webapp/WEB-INF/views/admin/reportList.jsp, EveryFit/src/main/webapp/WEB-INF/views/homeMoimSerach.jsp, EveryFit/src/main/webapp/WEB-INF/views/report/apply.jsp, EveryFit/src/main/webapp/WEB-INF/views/report/detail.jsp, EveryFit/src/main/webapp/WEB-INF/views/template/Footer.jsp, EveryFit/src/main/webapp/WEB-INF/views/template/Header.jsp, EveryFit/src/main/webapp/WEB-INF/views/template/adminHeader.jsp
=> 신고하기 회원 정보 삽입, 풋터 위치 수정

EveryFit/src/main/java/com/kh/EveryFit/configuration/InterceptorConfiguration.java, EveryFit/src/main/java/com/kh/EveryFit/controller/AppealController.java, EveryFit/src/main/java/com/kh/EveryFit/dao/AppealDao.java, EveryFit/src/main/java/com/kh/EveryFit/dao/AppealDaoImpl.java, EveryFit/src/main/java/com/kh/EveryFit/dto/AppealDto.java, EveryFit/src/main/java/com/kh/EveryFit/vo/AdminAppealSearchVO.java, EveryFit/src/main/resources/mybatis/appeal-mapper.xml, EveryFit/src/main/webapp/WEB-INF/views/appeal/add.jsp, EveryFit/src/main/webapp/WEB-INF/views/appeal/detail.jsp, EveryFit/src/main/webapp/WEB-INF/views/appeal/list.jsp, EveryFit/src/main/webapp/WEB-INF/views/error/MemberBlockException.jsp, EveryFit/src/main/webapp/WEB-INF/views/report/reportList.jsp, EveryFit/src/main/webapp/WEB-INF/views/template/adminHeader.jsp
=> 항소기능 구현 완료

EveryFit/src/main/java/com/kh/EveryFit/configuration/InterceptorConfiguration.java, EveryFit/src/main/java/com/kh/EveryFit/controller/AdminController.java, EveryFit/src/main/java/com/kh/EveryFit/controller/HomeController.java, EveryFit/src/main/java/com/kh/EveryFit/dao/AdminDao.java, EveryFit/src/main/java/com/kh/EveryFit/dao/AdminDaoImpl.java, EveryFit/src/main/resources/application.properties, EveryFit/src/main/resources/mybatis/admin-mapper.xml, EveryFit/src/main/webapp/WEB-INF/views/admin/mypage.jsp, EveryFit/src/main/webapp/WEB-INF/views/home.jsp
=> 홈페이지 내가 가입한 목록 추가

EveryFit/src/main/webapp/WEB-INF/views/faq/detail.jsp, EveryFit/src/main/webapp/WEB-INF/views/faq/list.jsp, EveryFit/src/main/webapp/WEB-INF/views/freeBoard/detail.jsp, EveryFit/src/main/webapp/WEB-INF/views/home.jsp, EveryFit/src/main/webapp/WEB-INF/views/moimBoard/detail.jsp
=> 게시판 글 권한에 따른 버튼 수정

EveryFit/src/main/webapp/WEB-INF/views/template/Header.jsp, EveryFit/src/main/webapp/WEB-INF/views/template/adminHeader.jsp
=> 회원 로그인시 회원가입 페이지 숨김처리

EveryFit/src/main/java/com/kh/EveryFit/controller/HomeController.java, EveryFit/src/main/java/com/kh/EveryFit/dao/AdminDao.java, EveryFit/src/main/java/com/kh/EveryFit/dao/AdminDaoImpl.java, EveryFit/src/main/resources/mybatis/admin-mapper.xml, EveryFit/src/main/webapp/WEB-INF/views/home.jsp
=> 내가 찜한 목록 구현중

EveryFit/src/main/webapp/WEB-INF/views/pay/list.jsp, EveryFit/src/main/webapp/WEB-INF/views/pay/premium.jsp
=> 나의결제리스트 디자인 수정

EveryFit/src/main/java/com/kh/EveryFit/rest/MoimRestController.java, EveryFit/src/main/java/com/kh/EveryFit/service/ChannelService.java, EveryFit/src/main/java/com/kh/EveryFit/service/ChannelServiceImpl.java, EveryFit/src/main/java/com/kh/EveryFit/vo/ChatListVO.java, EveryFit/src/main/java/com/kh/EveryFit/vo/ChatRoomVO.java, EveryFit/src/main/java/com/kh/EveryFit/websocket/ChatWebsocketServer.java, EveryFit/src/main/resources/mybatis/chat-mapper.xml, EveryFit/src/main/webapp/WEB-INF/views/moim/detail.jsp, EveryFit/src/main/webapp/WEB-INF/views/ws/default.jsp
=> 채팅 수정(회원이 계속 추가되는 오류)

EveryFit/src/main/java/com/kh/EveryFit/configuration/InterceptorConfiguration.java, EveryFit/src/main/webapp/WEB-INF/views/faq/list.jsp, EveryFit/src/main/webapp/WEB-INF/views/freeBoard/list.jsp, EveryFit/src/main/webapp/WEB-INF/views/freeBoard/photoList.jsp, EveryFit/src/main/webapp/WEB-INF/views/moimBoard/list.jsp, EveryFit/src/main/webapp/WEB-INF/views/template/Header.jsp, EveryFit/src/main/webapp/WEB-INF/views/template/adminHeader.jsp
=> 게시판 에니매이션 보여주기 추가

EveryFit/src/main/java/com/kh/EveryFit/configuration/InterceptorConfiguration.java, EveryFit/src/main/webapp/WEB-INF/views/error/MemberBlockException.jsp, EveryFit/src/main/webapp/WEB-INF/views/member/change.jsp, EveryFit/src/main/webapp/WEB-INF/views/member/login.jsp, EveryFit/src/main/webapp/WEB-INF/views/moimBoard/boardTable.jsp, EveryFit/src/main/webapp/WEB-INF/views/moimBoard/detail.jsp, EveryFit/src/main/webapp/WEB-INF/views/moimBoard/edit.jsp, EveryFit/src/main/webapp/WEB-INF/views/moimBoard/list.jsp, EveryFit/src/main/webapp/WEB-INF/views/product/list.jsp, EveryFit/src/main/webapp/WEB-INF/views/report/detail.jsp
=> 배포 경로 일부 수정

EveryFit/src/main/webapp/WEB-INF/views/home.jsp, EveryFit/src/main/webapp/WEB-INF/views/moim/detail.jsp
=> 배포준비로 인한 경로 수정
